server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      cookie:
        http-only: true
        same-site: lax

spring:
  application:
    name: pconlineshop
  profiles:
    default: dev
  thymeleaf:
    encoding: UTF-8
  messages:
    encoding: UTF-8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
  mail:
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
