INSERT INTO category (category_id, parent_id, category_name, description, display_order)
VALUES
(1, NULL, 'Mainboard', 'Motherboards for custom PC builds', 1),
(2, NULL, 'CPU', 'Desktop processors', 2),
(3, NULL, 'GPU', 'Graphics cards', 3),
(4, NULL, 'Memory', 'Desktop RAM kits', 4),
(5, NULL, 'Storage', 'SSD and HDD storage', 5),
(6, NULL, 'Case', 'PC cases', 6),
(7, NULL, 'Power Supply', 'Desktop power supplies', 7),
(8, NULL, 'Cooling', 'Air and liquid CPU coolers', 8),
(9, NULL, 'Gear', 'Peripherals, furniture, and gaming accessories', 9),
(10, NULL, 'Socket AM4', 'AMD AM4 socket', 100),
(11, NULL, 'Socket AM5', 'AMD AM5 socket', 101),
(12, NULL, 'Socket LGA1700', 'Intel LGA1700 socket', 102),
(13, NULL, 'Socket LGA1200', 'Intel LGA1200 socket', 103),
(14, NULL, 'Socket LGA1151', 'Intel LGA1151 socket', 104),
(15, NULL, 'ATX', 'ATX form factor', 300),
(16, NULL, 'Micro-ATX', 'Micro-ATX form factor', 301),
(17, NULL, 'Mini-ITX', 'Mini-ITX form factor', 302),
(18, NULL, 'E-ATX', 'E-ATX form factor', 303),
(19, NULL, 'DDR4', 'DDR4 memory', 400),
(20, NULL, 'DDR5', 'DDR5 memory', 401),
(21, NULL, 'PCIe 3.0', 'PCIe 3.0 interface', 500),
(22, NULL, 'PCIe 4.0', 'PCIe 4.0 interface', 501),
(23, NULL, 'PCIe 5.0', 'PCIe 5.0 interface', 502),
(24, NULL, 'SATA', 'SATA storage interface', 600),
(25, NULL, 'M.2 NVMe', 'M.2 NVMe storage interface', 601),
(26, NULL, 'M.2 SATA', 'M.2 SATA storage interface', 602),
(27, NULL, 'ATX PSU', 'ATX PSU form factor', 700),
(28, NULL, 'SFX PSU', 'SFX PSU form factor', 701),
(29, NULL, 'Air Cooling', 'Air cooling', 800),
(30, NULL, 'AIO Cooling', 'All-in-one liquid cooling', 801),
(31, 9, 'Keyboard', 'Gaming and productivity keyboards', 900),
(32, 9, 'Mouse', 'Gaming and productivity mice', 901),
(33, 9, 'Monitor', 'Gaming and productivity monitors', 902),
(34, 9, 'Add-on', 'Setup accessories and add-ons', 903),
(35, 9, 'Headset', 'Gaming headsets and audio headsets', 904),
(36, 9, 'Mousepad', 'Mousepads and desk mats', 905),
(37, 9, 'Speaker', 'Desktop speakers', 906),
(38, 9, 'Chair', 'Gaming and office chairs', 907),
(39, 9, 'Desk', 'Gaming desks and setup furniture', 908),
(40, 9, 'Webcam', 'Streaming and video call webcams', 909),
(41, 9, 'Microphone', 'USB and streaming microphones', 910),
(42, 9, 'Controller', 'Game controllers', 911),
(43, NULL, 'GDDR6', 'GDDR6 graphics memory', 520),
(44, NULL, 'GDDR6X', 'GDDR6X graphics memory', 521);

ALTER TABLE category AUTO_INCREMENT = 100;

INSERT INTO brand (brand_id, name, description, website, status)
VALUES
(1, 'ASUS', 'ASUS hardware and gaming products', 'https://www.asus.com', TRUE),
(2, 'MSI', 'MSI gaming hardware', 'https://www.msi.com', TRUE),
(3, 'Gigabyte', 'Gigabyte PC hardware', 'https://www.gigabyte.com', TRUE),
(4, 'Intel', 'Intel CPUs and platform technology', 'https://www.intel.com', TRUE),
(5, 'AMD', 'AMD CPUs and Radeon graphics', 'https://www.amd.com', TRUE),
(6, 'NVIDIA', 'NVIDIA graphics technology', 'https://www.nvidia.com', TRUE),
(7, 'Corsair', 'Memory, PSUs, cases, cooling, and gaming gear', 'https://www.corsair.com', TRUE),
(8, 'G.Skill', 'High-performance memory kits', 'https://www.gskill.com', TRUE),
(9, 'Kingston', 'Memory and SSD storage', 'https://www.kingston.com', TRUE),
(10, 'Cooler Master', 'Cases, cooling, PSUs, and peripherals', 'https://www.coolermaster.com', TRUE),
(11, 'Seagate', 'SSD and HDD storage', 'https://www.seagate.com', TRUE),
(12, 'Western Digital', 'SSD and HDD storage', 'https://www.westerndigital.com', TRUE),
(13, 'NZXT', 'PC cases, cooling, and motherboards', 'https://nzxt.com', TRUE),
(14, 'Lian Li', 'PC cases and cooling hardware', 'https://lian-li.com', TRUE),
(15, 'Fractal Design', 'PC cases and cooling hardware', 'https://www.fractal-design.com', TRUE),
(16, 'Phanteks', 'PC cases and cooling hardware', 'https://www.phanteks.com', TRUE),
(17, 'Thermaltake', 'Cases, PSUs, cooling, and gaming gear', 'https://www.thermaltake.com', TRUE),
(18, 'Noctua', 'Premium air cooling', 'https://noctua.at', TRUE),
(19, 'Deepcool', 'Cooling, cases, and PSUs', 'https://www.deepcool.com', TRUE),
(20, 'Thermalright', 'Air cooling hardware', 'https://www.thermalright.com', TRUE),
(21, 'be quiet!', 'Quiet PC cases, cooling, and PSUs', 'https://www.bequiet.com', TRUE),
(22, 'Arctic', 'Cooling hardware', 'https://www.arctic.de', TRUE),
(23, 'Crucial', 'Memory and SSD storage by Micron', 'https://www.crucial.com', TRUE),
(24, 'Teamgroup', 'Memory and SSD storage', 'https://www.teamgroupinc.com', TRUE),
(25, 'Samsung', 'SSD storage and monitors', 'https://www.samsung.com', TRUE),
(26, 'SK Hynix', 'SSD storage', 'https://ssd.skhynix.com', TRUE),
(27, 'Sabrent', 'SSD storage', 'https://sabrent.com', TRUE),
(28, 'Adata', 'Memory, SSD storage, and gaming gear', 'https://www.adata.com', TRUE),
(29, 'SanDisk', 'Flash storage and SSDs', 'https://www.sandisk.com', TRUE),
(30, 'Toshiba', 'HDD storage', 'https://www.toshiba-storage.com', TRUE),
(31, 'Seasonic', 'Power supplies', 'https://seasonic.com', TRUE),
(32, 'EVGA', 'Graphics cards, motherboards, and PSUs', 'https://www.evga.com', TRUE),
(33, 'FSP', 'Power supplies', 'https://www.fsplifestyle.com', TRUE),
(34, 'Antec', 'Cases, PSUs, and fans', 'https://www.antec.com', TRUE),
(35, 'Hyte', 'PC cases', 'https://hyte.com', TRUE),
(36, 'ASRock', 'Motherboards and graphics cards', 'https://www.asrock.com', TRUE),
(37, 'Golden Field', 'Cases and PSUs', 'https://www.goldenfield.com.cn', TRUE),
(38, 'SAMA', 'Cases and cooling hardware', 'https://www.sama.com', TRUE),
(39, 'KENOO', 'Budget PC cases', 'https://www.kenoo.com', TRUE),
(40, 'Vision', 'Budget PC cases', 'https://www.visioncase.com', TRUE),
(41, 'Techware', 'Cases and gaming accessories', 'https://www.techware.com', TRUE),
(42, 'Xigmatek', 'Cases, PSUs, and cooling hardware', 'https://www.xigmatek.com', TRUE),
(43, 'VSP', 'Budget cases and PSUs', 'https://www.vspgroup.vn', TRUE),
(44, 'Logitech', 'Gaming mice, keyboards, webcams, and audio gear', 'https://www.logitechg.com', TRUE),
(45, 'Razer', 'Gaming peripherals and accessories', 'https://www.razer.com', TRUE),
(46, 'SteelSeries', 'Gaming peripherals and headsets', 'https://steelseries.com', TRUE),
(47, 'HyperX', 'Gaming headsets, microphones, and accessories', 'https://hyperx.com', TRUE),
(48, 'Keychron', 'Mechanical keyboards', 'https://www.keychron.com', TRUE),
(49, 'Akko', 'Mechanical keyboards and switches', 'https://en.akkogear.com', TRUE),
(50, 'LG', 'Gaming and productivity monitors', 'https://www.lg.com', TRUE),
(51, 'Dell', 'Monitors and PC hardware', 'https://www.dell.com', TRUE),
(52, 'Creative', 'Desktop audio hardware', 'https://creative.com', TRUE),
(53, 'Secretlab', 'Gaming chairs and desks', 'https://secretlab.co', TRUE),
(54, 'Elgato', 'Streaming hardware and setup accessories', 'https://www.elgato.com', TRUE),
(55, 'Blue', 'USB microphones', 'https://www.logitechg.com', TRUE),
(56, 'Microsoft', 'Xbox controllers and PC accessories', 'https://www.microsoft.com', TRUE),
(57, 'ViewSonic', 'Gaming and productivity monitors', 'https://www.viewsonic.com', TRUE),
(58, 'AOC', 'Gaming and productivity monitors', 'https://aoc.com', TRUE),
(59, 'Edifier', 'Desktop speakers and audio hardware', 'https://www.edifier.com', TRUE);

ALTER TABLE brand AUTO_INCREMENT = 100;
